### PR TITLE
fix feed url in pdf file not saved

### LINKED ISSUE #3180: RSS links to PDFs do not properly set subscription information
If a link in RSS points to a PDF item, i believe puppeteer-parse detects that this is a PDF and then creates a separate download, so this is why items don't get their subscription information set.

### PR DESCRIPTION
**Pull request by sywhb**
Fix #3180

### CODE REVIEW

**Comment by sywhb** [comment]
> LGTM, one thing i can't tell from the PR though, will the `RSS` label also be added if feedUrl is non-null?

Hah, no but yeah we should. Let me add that part

File: packages/api/src/services/labels.ts [hunk 1]
```diff
@@ -65,6 +65,33 @@ export const findOrCreateLabels = async (
...
+  userId: string,
+  labels?: CreateLabelInput[] | null,
+  rssFeedUrl?: string | null,
+  pubsub?: PubsubClient,
+  skipPubSub?: boolean
+) => {
+  if (rssFeedUrl) {
+    // add rss label to labels
+    labels = (labels || []).concat({ name: 'RSS' })
+  }
```
Comment (sywhb) [inline packages/api/src/services/labels.ts:79]: @jacksonh This will add RSS label to the library item if feedUrl is not null

**Review by jacksonh — APPROVED** [review]
